import type { Metadata } from 'next'
import './globals.css'
import { Figtree, Pp, Pretendard } from '@/utils/Font'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="kr"
      className={`${Figtree.variable} ${Pp.variable} ${Pretendard.variable}`}>
      <body
        className={`${Figtree.className} ${Pp.className} ${Pretendard.className}`}>
        {children}
      </body>
    </html>
  )
}
